import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container py-20">
        <div className="mx-auto max-w-4xl">
          <h1 className="mb-8 text-4xl font-bold">Terms of Service</h1>
          <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-sm">Last updated: December 31, 2025</p>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing and using PrintFlow, you accept and agree to be bound by these Terms of Service. If you do
                not agree to these terms, please do not use our platform.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
              <p>
                PrintFlow provides an AI-powered automation platform for Print-on-Demand sellers. Our services include
                design generation, content creation, product publishing, analytics, and store management tools.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">3. Account Registration</h2>
              <p>To use PrintFlow, you must:</p>
              <ul className="list-disc space-y-2 pl-6">
                <li>Be at least 18 years of age</li>
                <li>Provide accurate and complete information</li>
                <li>Maintain the security of your account credentials</li>
                <li>Accept responsibility for all activities under your account</li>
                <li>Notify us immediately of any unauthorized access</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">4. User Responsibilities</h2>
              <p>You agree to:</p>
              <ul className="list-disc space-y-2 pl-6">
                <li>Use the service only for lawful purposes</li>
                <li>Not infringe on intellectual property rights</li>
                <li>Comply with all applicable laws and regulations</li>
                <li>Not attempt to hack or disrupt the platform</li>
                <li>Not use the service to create offensive or illegal content</li>
                <li>Verify all AI-generated content before publishing</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">5. Intellectual Property</h2>
              <h3 className="text-xl font-semibold text-foreground">5.1 Your Content</h3>
              <p>
                You retain all rights to designs and content you create using PrintFlow. You grant us a license to use
                your content solely to provide and improve our services.
              </p>

              <h3 className="text-xl font-semibold text-foreground">5.2 Our Platform</h3>
              <p>
                PrintFlow and its underlying technology are protected by intellectual property laws. You may not copy,
                modify, or reverse engineer any part of our platform.
              </p>

              <h3 className="text-xl font-semibold text-foreground">5.3 AI-Generated Content</h3>
              <p>
                Content generated by our AI becomes yours to use commercially. However, you are solely responsible for
                ensuring it doesn't infringe on third-party rights.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">6. Payment and Billing</h2>
              <ul className="list-disc space-y-2 pl-6">
                <li>Subscription fees are billed in advance</li>
                <li>All fees are non-refundable except as required by law</li>
                <li>We reserve the right to change pricing with notice</li>
                <li>Failed payments may result in service suspension</li>
                <li>You're responsible for all taxes</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">7. Service Availability</h2>
              <p>
                We strive for 99.9% uptime but cannot guarantee uninterrupted service. We may modify, suspend, or
                discontinue features at any time with reasonable notice.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">8. Disclaimer of Warranties</h2>
              <p>
                PrintFlow is provided "as is" without warranties of any kind. We do not guarantee that AI-generated
                content will be error-free, profitable, or suitable for your specific needs.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">9. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, PrintFlow shall not be liable for any indirect, incidental, or
                consequential damages arising from your use of the service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">10. Termination</h2>
              <p>
                Either party may terminate this agreement at any time. Upon termination, your access to the platform
                will cease, but products already published to your stores remain yours.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">11. Governing Law</h2>
              <p>
                These terms are governed by the laws of the jurisdiction where PrintFlow operates, without regard to
                conflict of law provisions.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">12. Changes to Terms</h2>
              <p>
                We may modify these terms at any time. Continued use of the service after changes constitutes acceptance
                of the new terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">13. Contact Information</h2>
              <p>
                For questions about these Terms of Service, contact us at legal@printflow.com or through our contact
                page.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
