import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import Link from "next/link"
import { ArrowRight } from "lucide-react"

export default function FAQPage() {
  const faqs = [
    {
      question: "What is PrintFlow?",
      answer:
        "PrintFlow is an AI-powered automation platform designed specifically for Print-on-Demand sellers. It helps you create products, optimize listings, and scale your business faster using advanced artificial intelligence.",
    },
    {
      question: "Which POD platforms does PrintFlow support?",
      answer:
        "PrintFlow supports all major Print-on-Demand platforms including Etsy, Redbubble, Merch by Amazon, Printful, Printify, Teespring, TeePublic, Society6, and more. We're constantly adding new integrations based on user demand.",
    },
    {
      question: "Do I need design skills to use PrintFlow?",
      answer:
        "No design skills required! Our AI handles all the creative work. You simply review and approve the designs generated by our system. However, you can also upload your own designs if you prefer.",
    },
    {
      question: "How does the AI create designs?",
      answer:
        "Our AI uses advanced machine learning models trained on millions of successful POD products. It analyzes current trends, understands what sells, and generates unique designs optimized for your target niche and platform.",
    },
    {
      question: "Is my data and designs secure?",
      answer:
        "Absolutely. We use bank-level encryption and are SOC 2 compliant. Your designs and data are 100% private and never shared with anyone. We also have comprehensive trademark checking to protect you from legal issues.",
    },
    {
      question: "How much time can I save with PrintFlow?",
      answer:
        "Most users report saving 10-20 hours per week on product creation and listing management. Some power users who run multiple stores save even more. The platform handles tasks that would normally take hours in just minutes.",
    },
    {
      question: "Can I use PrintFlow with multiple stores?",
      answer:
        "Yes! PrintFlow is designed to manage multiple stores across different platforms from a single dashboard. Many of our users run 5+ stores simultaneously using our platform.",
    },
    {
      question: "What happens to my products if I cancel?",
      answer:
        "All products published to your stores remain yours forever. If you cancel, you simply lose access to the PrintFlow automation features. Your existing products and stores are unaffected.",
    },
    {
      question: "Does PrintFlow check for trademark issues?",
      answer:
        "Yes, we have built-in trademark checking that flags potential issues before you publish. This helps protect your store from takedowns and legal problems. However, you're still responsible for reviewing all content.",
    },
    {
      question: "Can I customize the AI-generated content?",
      answer:
        "All AI-generated designs, titles, descriptions, and tags can be edited before publishing. You have complete control over what goes live in your store.",
    },
    {
      question: "How does billing work?",
      answer:
        "We offer flexible subscription plans based on your needs. Start with a free trial to test the platform. After that, choose a plan that fits your business size. No hidden fees, and you can cancel anytime.",
    },
    {
      question: "Do you offer support?",
      answer:
        "Yes! We offer comprehensive support including documentation, video tutorials, email support, and live chat. Our team includes experienced POD sellers who understand your challenges.",
    },
    {
      question: "Can I integrate PrintFlow with my existing workflow?",
      answer:
        "Yes, PrintFlow is designed to complement your existing tools. We integrate with popular POD platforms and can fit into any workflow. Many users gradually transition to full automation.",
    },
    {
      question: "What makes PrintFlow different from other automation tools?",
      answer:
        "Unlike template-based tools, PrintFlow uses true AI that learns and adapts. It's built specifically for POD sellers by POD sellers. Our AI understands trends, generates unique content, and continuously optimizes for better results.",
    },
    {
      question: "Is there a limit to how many products I can create?",
      answer:
        "Limits depend on your subscription plan. Even our basic plans offer generous product creation limits. Enterprise users get unlimited product generation and publishing.",
    },
  ]

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main>
        {/* Hero Section */}
        <section className="container py-20 md:py-32">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="mb-6 text-balance text-4xl font-bold md:text-5xl lg:text-6xl">Frequently Asked Questions</h1>
            <p className="mb-8 text-balance text-lg text-muted-foreground md:text-xl">
              Everything you need to know about PrintFlow and how it can help grow your Print-on-Demand business.
            </p>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="container pb-20 md:pb-32">
          <div className="mx-auto max-w-3xl">
            <Accordion type="single" collapsible className="space-y-4">
              {faqs.map((faq, index) => (
                <AccordionItem
                  key={index}
                  value={`item-${index}`}
                  className="rounded-lg border border-border bg-card px-6"
                >
                  <AccordionTrigger className="text-left hover:no-underline">{faq.question}</AccordionTrigger>
                  <AccordionContent className="text-muted-foreground">{faq.answer}</AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>

        {/* Contact Section */}
        <section className="container pb-20 md:pb-32">
          <div className="mx-auto max-w-3xl rounded-2xl border border-border bg-card p-8 text-center md:p-12">
            <h2 className="mb-4 text-2xl font-bold md:text-3xl">Still Have Questions?</h2>
            <p className="mb-8 text-balance text-muted-foreground">
              Can't find what you're looking for? Our support team is here to help.
            </p>
            <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link href="/contact">
                <Button size="lg">Contact Support</Button>
              </Link>
              <Link href="/signup">
                <Button size="lg" variant="outline" className="bg-transparent">
                  Start Free Trial
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
